version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: / 
    destination: /app
hooks:
  ApplicationStop:
    - location: /.aws/cd_scripts/stop_compose.sh
      runas: root
  BeforeInstall:
    - location: /.aws/cd_scripts/login_ecr.sh
      runas: root
  AfterInstall:
    - location: /.aws/cd_scripts/install_dependancies.sh
      runas: root
  ApplicationStart:
    - location: /.aws/cd_scripts/start_compose.sh
      runas: root

