version: '3'

services:
  app:
    build: .
    networks:
      - board
    depends_on:
      - db
    environment:
      DB_HOST: db
    volumes:
      - ./.env:/app/.env:ro
  proxy:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - board
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    image: mariadb
    volumes:
      - ~/docker/board/data:/var/lib/mysql
      - ./database.sql:/db-base.sql
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - board
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: board

networks:
  board:
