version: '3'

services:
  app:
    build: .
    ports:
      - 80:8080
    networks:
      - board
    depends_on:
      - db
    environment:
      DB_HOST: db
    volumes:
      - ./.env:/app/.env:ro
  db:
    image: mariadb
    volumes:
      - ~/docker/board/my.cnf.d:/etc/mysql/conf.d:ro
      - ~/docker/board/data:/var/lib/mysql
      - ./database.sql:/base-structure.sql
      - ./init-database.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - board
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: board

networks:
  board:


