version: '3'

services:
  app:
    image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/devlog-deployment:latest
    ports:
      - 80:8080
    networks:
      - board
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: mariadb
    volumes:
      - /app-data/board/my.cnf.d:/etc/mysql/conf.d:ro
      - /app-data/board/data:/var/lib/mysql
      - /app/database.sql:/base-structure.sql
      - /app/init-database.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - board
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: board

networks:
  board:


