version: '3'

services:
  app:
    image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/devlog-deployment:latest
    ports:
      - 80:8080
    networks:
      - board
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: mariadb
    volumes:
      - /app-data:/var/lib/mysql
      - /app/board/assets:/assets
      - /app/board/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - board
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: board

networks:
  board:
