version: '3'

services:
  app:
    image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/devlog-deployment:latest
    networks:
      - board
    depends_on:
      - db
    environment:
      DB_HOST: db
  proxy:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - board
    volumes:
      - /app/board/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: devlog-httplog
        awslogs-create-group: true
  db:
    image: mariadb
    volumes:
      - /app-data:/var/lib/mysql
      - /app/board/assets:/assets
      - /app/board/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - board
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: board

networks:
  board:
